# Generated by Django 4.2.2 on 2023-07-20 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Package ID', primary_key=True, serialize=False)),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='registration date')),
                ('consumed_hours', models.CharField(default='00:00:00 Hrs', max_length=100, verbose_name='consumed hours')),
                ('remaining_hours', models.CharField(default='00:00:00 Hrs', max_length=100, verbose_name='remaining hours')),
                ('consumed_time', models.DurationField(default=datetime.timedelta(0), verbose_name='consumed time')),
                ('remaining_time', models.DurationField(default=datetime.timedelta(0), verbose_name='remaining_time')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Finalizado')], default=True, help_text='Select the package status', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Enrolled Package',
                'verbose_name_plural': 'Enrolled Packages',
                'ordering': ['student__user__username'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=1, verbose_name='hours')),
            ],
            options={
                'verbose_name': 'package type',
                'verbose_name_plural': 'package types',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='session ID', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('session_duration', models.DurationField(blank=True, null=True, verbose_name='session duration')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('enrolled_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.enrolledpackage', verbose_name='enrolled package')),
                ('subjects', models.ManyToManyField(related_name='sessions', to='school.subject', verbose_name='subjects')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
