# Generated by Django 4.2.2 on 2023-08-10 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='session date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='note'),
        ),
    ]
