# Generated by Django 4.2.2 on 2023-08-27 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_enrolledpackage_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpackage',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='registration date'),
        ),
    ]
