# Generated by Django 4.2.2 on 2023-08-10 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_session_session_date_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpackage',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
        ),
    ]
