# Generated by Django 4.2.2 on 2023-08-10 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_enrolledpackage_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 8, 10), null=True, verbose_name='end time'),
        ),
    ]
