# Generated by Django 4.2.2 on 2023-08-27 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_enrolledpackage_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpackage',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
    ]
