# Generated by Django 4.2.2 on 2023-08-10 09:22

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, default=school.models.default_end_time, null=True, verbose_name='end time'),
        ),
    ]
